name: Check PR Source Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Only run when PR target is main

jobs:
  verify-source:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar branch de origem
        run: |
          echo "Branch de origem: ${{ github.head_ref }}"
          echo "Branch de destino: ${{ github.base_ref }}"
          
          if [ "${{ github.head_ref }}" != "development" ]; then
            echo "Erro: Pull requests para a 'main' só podem ser criados a partir da branch 'development'."
            exit 1
          fi